apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-portsadapterbackendimplementation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-portsadapterbackendimplementation
  template:
    metadata:
      labels:
        app: api-portsadapterbackendimplementation
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: api-portsadapterbackendimplementation
        image: fullhendrix/portsadapterbackendimplementation
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
